packages:
  - 'common'
  - 'packages/*'

catalog:
  # dependencies
  '@wangeditor/editor-for-vue': ^5.1.12
  '@element-plus/icons-vue': ^2.3.1
  'axios': ^1.7.9
  'echarts': ^5.3.3
  'element-plus': ^2.9.4
  'highlight.js': ^11.11.1
  'lodash-es': ^4.17.21
  'moment': ^2.30.1
  'pinia': ^3.0.1
  'vue': ^3.5.13
  'vue-router': ^4.5.0
  '@tsparticles/vue3': 3.0.1
  '@tsparticles/slim': 3.8.1
  # devDependencies
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/eslint-config-prettier': ^10.2.0
  'autoprefixer': ^10.4.14
  'concurrently': ^9.1.2
  'eslint': ^9.20.1
  'eslint-plugin-vue': ^9.32.0
  'less': ^4.2.2
  'postcss': ^8.5.3
  'prettier': ^3.5.1
  'tailwindcss': ^3.4.17
  'vite': ^6.2.0
  'unplugin-auto-import': ^19.1.2
  'unplugin-vue-components': ^28.4.1
  'rollup-plugin-visualizer': ^5.14.0
